name: Pull on Cassini

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  pull-remote:
    runs-on: ubuntu-latest
    env:
      HOST: cassini.cs.kent.edu
      USER: colorsplode            # change if needed
      REMOTE_DIR: ~/ColorSplode
      ID_ED25519: ${{ secrets.ID_ED25519 }}
      KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.7.0
        with:
            key: $ID_ED25519 
            name: id_ed25519
            known_hosts: $KNOWN_HOSTS
          
      - name: Pull latest on Cassini
        run: |
          ssh -o BatchMode=yes "$USER@$HOST" 'cd "$REMOTE_DIR" && git pull --ff-only'

        
