name: Pull on Cassini

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  pull-remote:
    runs-on: ubuntu-latest
    env:
      HOST: cassini.cs.kent.edu
      USER: colorsplode            # change if needed
      REMOTE_DIR: /home/colorsplode/web
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_ED25519 }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Pull latest on Cassini
        run: |
          echo $ ssh -o BatchMode=yes $USER@$HOST 'cd $REMOTE_DIR && git pull --ff-only'
          ssh -o BatchMode=yes $USER@$HOST 'cd $REMOTE_DIR && git pull --ff-only'

        
